import moment from 'moment';

export const today = new Date(new Date().setHours(0, 0, 0, 0));
export const currentMoment = moment();
export const oneYearBeforeDate = new Date(
  new Date().setMonth(new Date().getMonth() - 12),
);
export const calendarYearRange = 156;
export const monthNames = [
  { title: 'January', value: '1' },
  { title: 'February', value: '2' },
  { title: 'March', value: '3' },
  { title: 'April', value: '4' },
  { title: 'May', value: '5' },
  { title: 'June', value: '6' },
  { title: 'July', value: '7' },
  { title: 'August', value: '8' },
  { title: 'September', value: '9' },
  { title: 'October', value: '10' },
  { title: 'November', value: '11' },
  { title: 'December', value: '12' },
];
export const calendarStartYear = 1900;

// When we have relationShip types
export const relationshipTypes = [
  { value: '999', title: 'OTHERS' },
  { value: 'AUD', title: 'AUDITOR' },
  { value: 'AUN', title: 'AUNT' },
  { value: 'AUS', title: 'AUTHORIZED SIGNATORY' },
  { value: 'BAK', title: 'BANKER' },
  { value: 'BENO', title: 'BENEFICIAL OWNER' },
  { value: 'BIL', title: 'BROTHER IN LAW' },
  { value: 'BRO', title: 'BROTHER' },
  { value: 'BSP', title: 'BUSINESS PARTNER' },
  { value: 'CG', title: 'CORPORATE GUARANTEE' },
  { value: 'CNT', title: 'CONTACT PERSON' },
  { value: 'COB', title: 'COUSIN BROTHER' },
  { value: 'COD', title: 'CO-DIRECTOR' },
  { value: 'COP', title: 'CO-PARTNERS' },
  { value: 'COPAR', title: 'COPARCENER' },
  { value: 'COS', title: 'COUSIN SISTER' },
  { value: 'DAU', title: 'DAUGHTER' },
  { value: 'DIL', title: 'DAUGHTER IN LAW' },
  { value: 'DIR', title: 'DIRECTOR' },
  { value: 'EMP', title: 'EMPLOYEE' },
  { value: 'EMR', title: 'EMPLOYER' },
  { value: 'EXE', title: 'EXECUTOR' },
  { value: 'EXECU', title: 'EXECUTOR, ADMINISTOR' },
  { value: 'FAT', title: 'FATHER' },
  { value: 'FIL', title: 'FATHER IN LAW' },
  { value: 'FRD', title: 'FRIEND' },
  { value: 'GFM', title: 'GRAND FATHER (MATERNAL)' },
  { value: 'GFP', title: 'GRAND FATHER (PATERNAL)' },
  { value: 'GMM', title: 'GRAND MOTHER (MATERNAL)' },
  { value: 'GMP', title: 'GRAND MOTHER (PATERNAL)' },
  { value: 'GRASO', title: 'GRAND SON' },
  { value: 'GRD', title: 'GRAND DAUGHTER' },
  { value: 'GUA', title: 'GUARANTOR' },
  { value: 'HOL', title: 'HOLDING CO' },
  { value: 'HUS', title: 'HUSBAND' },
  { value: 'INT', title: 'INTRODUCER' },
  { value: 'KAR', title: 'KARTA' },
  { value: 'LEG', title: 'LEGAL GUARDIAN' },
  { value: 'LOA', title: 'LETTER OF AUTHORITY' },
  { value: 'MIL', title: 'MOTHER IN LAW' },
  { value: 'MNDT', title: 'MANDATEE' },
  { value: 'MOT', title: 'MOTHER' },
  { value: 'NEE', title: 'NIECE' },
  { value: 'NEP', title: 'NEPHEW' },
  { value: 'NGU', title: 'NATURAL GUARDIAN' },
  { value: 'NOM', title: 'NOMINEE' },
  { value: 'PARTN', title: 'PARTNER' },
  { value: 'POA', title: 'POWER OF ATTORNEY HOLDER' },
  { value: 'PRO', title: 'PROPRIETOR' },
  { value: 'REL', title: 'RELATIVE' },
  { value: 'RIM', title: 'RELATIONSHIP MANAGER' },
  { value: 'SELF', title: 'NO NOMINATION REQUESTED' },
  { value: 'SHR', title: 'SHAREHOLDER' },
  { value: 'SIL', title: 'SON IN LAW' },
  { value: 'SIS', title: 'SISTER' },
  { value: 'SOLPR', title: 'SOLE PROPRIETOR' },
  { value: 'SON', title: 'SON' },
  { value: 'SSL', title: 'SISTER IN LAW' },
  { value: 'SUB', title: 'SUBSIDIARY' },
  { value: 'TRU', title: 'TRUSTEE' },
  { value: 'UG', title: 'UNDER GUARDIAN' },
  { value: 'UNC', title: 'UNCLE' },
  { value: 'WIF', title: 'WIFE' },
  { value: 'WAR', title: 'WARDEN' },
  { value: 'LOC', title: 'LETTER OF COMFORT' },
  { value: 'LOU', title: 'LETTER OF UNDERTAKING' },
  { value: 'MD', title: 'MANAGING DIRECTOR' },
  { value: 'MH', title: 'MANDATE HOLDER' },
  { value: 'SBLC', title: 'STAND BY LETTER OF CREDIT' },
  { value: 'SLF', title: 'GROUP PRIMARY' },
];

export const DateTimeFormat = {
  'DATE_FORMAT_DD.MM.YYYY': 'DD.MM.YYYY',
  'DATE_FORMAT_DD-MM-YYYY': 'DD-MM-YYYY',
};
