export const APP_CONFIG = process.env.NEXT_PUBLIC_APP_CONFIG;
export const APP_ROLE = process.env.NEXT_PUBLIC_APP_ROLE;
export const APPID_SUFFIX = process.env.NEXT_PUBLIC_APPID_SUFFIX;
export const IDENTIFIER = process.env.NEXT_PUBLIC_IDENTIFIER;
export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME;
export const APP_URL_SCHEME = process.env.NEXT_PUBLIC_APP_URL_SCHEME;
export const URL_HOST = process.env.NEXT_PUBLIC_URL_HOST;
export const SSL_PRIMARY_HOST = process.env.NEXT_PUBLIC_SSL_PRIMARY_HOST;
export const SSL_SECONDARY_HOST = process.env.NEXT_PUBLIC_SSL_SECONDARY_HOST;
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const WEB_APP_URL = process.env.NEXT_PUBLIC_WEB_APP_URL;
export const API_REQUEST_TIMEOUT = process.env.NEXT_PUBLIC_API_REQUEST_TIMEOUT;
export const ENCRYPTION_STATUS = process.env.NEXT_PUBLIC_ENCRYPTION_STATUS;
export const PINNING_STATUS = process.env.NEXT_PUBLIC_PINNING_STATUS;
export const STRAPI_BASE_URL = process.env.NEXT_PUBLIC_STRAPI_BASE_URL;
export const IS_PRE_AUTH_ENABLE = process.env.NEXT_PUBLIC_IS_PRE_AUTH_ENABLE;
export const CONFIG_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_CONFIG_MANAGEMENT_URL;
export const INIT_SERVICE_URL = process.env.NEXT_PUBLIC_INIT_SERVICE_URL;
export const AUTH_SERVICE_URL = process.env.NEXT_PUBLIC_AUTH_SERVICE_URL;
export const CUSTOMER_SERVICE_URL =
  process.env.NEXT_PUBLIC_CUSTOMER_SERVICE_URL;
export const CONSENT_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_CONSENT_MANAGEMENT_URL;
export const ACCOUNT_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_ACCOUNT_MANAGEMENT_URL;
export const REMITTANCE_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_REMITTANCE_MANAGEMENT_URL;
export const PAYMENT_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_PAYMENT_MANAGEMENT_URL;
export const MASTER_MANAGEMENT_URL =
  process.env.NEXT_PUBLIC_MASTER_MANAGEMENT_URL;
export const IS_LOOKOUT_SDK_INITIALIZE =
  process.env.NEXT_PUBLIC_IS_LOOKOUT_SDK_INITIALIZE;
export const IS_ROOTED = process.env.NEXT_PUBLIC_IS_ROOTED;
export const MOENGAGE_APP_ID = process.env.NEXT_PUBLIC_MOENGAGE_APP_ID;
export const MOENGAGE_ENV = process.env.NEXT_PUBLIC_MOENGAGE_ENV;
