export const LOOKOUT_API_KEY_ANDROID = 'ENV_LOOKOUT_API_KEY_ANDROID';
export const LOOKOUT_API_KEY_IOS = 'ENV_LOOKOUT_API_KEY_ANDROID';
export const X_IBL_CLIENT_ID = 'ENV_X_IBL_CLIENT_ID';
export const X_IBL_CLIENT_SECRET = 'ENV_X_IBL_CLIENT_SECRET';
export const USER_EXPERIOR_SDK_KEY = 'ENV_USER_EXPERIOR_SDK_KEY';
export const PUBLICKEYPEM = `ENV_PUBLICKEYPEM`;
